spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: swe
      port: 27017
      host: host.docker.internal
      auto-index-creation: true

